
---

  - name: CONFIGURE BANNER FROM FILE
    net_banner:
      banner: login
      text: "{{ lookup('file', './vars/login_banner.cfg') }}"
      state: present


#  - name: BASE CONFIG TEMPLATE  
#    ios_config:   
#      provider: "{{ provider }}" 
#      src: base_config.j2
      
#  - name: OSPF CONFIG TEMPLATE  
#    ios_config:   
#      src: ospf_config.j2
#      save: no     

  - name: INTERFACE CONFIG TEMPLATE
    ios_config:
      src: interface_aj.j2
      authorize: yes

#  - name: CONFIGURE BANNER FROM FILE
#    net_banner:
#      banner: login
#      text: "{{ lookup('file', './vars/login_banner.cfg') }}"
#      state: present


