---


# tasks file for Ansible_Cisco_ios_12.2_hardening_w-template





- hosts: ios
  gather_facts: no
  connection: local

  tasks:
  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"


  - name: HARDENING TEMPLATE  
    ios_config:   
      provider: "{{ provider }}" 
      src: if_device_os.j2
      save: no


  - name: CONFIGURE BANNER FROM FILE
    ios_banner:
      provider: "{{ provider }}"
      authorize: yes
      banner: login
      text: "{{ lookup('file', './vars/raw_banner.cfg') }}"
      state: present


